### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by MariiaZolotarova** [MariiaZolotarova/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by MariaDyachenko** [comment]
Я захоплююся грою в гольф. Є членом клубу Winged Foot Golf Club в Мамаронеке, штат Нью-Йорк, а також регулярно беру участь в змаганнях на своїх майданчиках. Я фанат Федора Емельяненко і не пропустив жодного його бою на території США. Я вболівальник американської футбольної команди Нью-Інгленд Петріотс.
