### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by MariiaZolotarova** [MariiaZolotarova/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by MariaDyachenko** [comment]
https://twitter.com/realdonaldtrump
https://www.instagram.com/realDonaldTrump/
https://www.facebook.com/DonaldTrump/
