### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by MariiaZolotarova** [MariiaZolotarova/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by MariaDyachenko** [comment]
Народився 14 червня 1946 року в районі Джамейка (Куїнс, Нью-Йорк).
1968 р. - після закінчення Вортона отримав ступінь бакалавра наук з економіки та спеціалізацію в сфері фінансів.
1971 році переїхав на Манхеттен
1995 р. - об'єднання казино в відкриту акціонерну компанію Trump Hotels & Casino Resorts.
З кінця 1990-х працював над декількома проектами, пов'язаними з будівництвом хмарочосів - готелів і офісних будівель.
16 червня 2015 року оголосив про те, що вступаю в боротьбу за пост президента США.
8 листопада 2016 здобув перемогу на виборах президента США, обійшовши кандидата від Демократичної партії Хілларі Клінтон.
20 січня 2017 року відбулася церемонія інавгурації 45-го президента США Дональда Трампа.

**Comment by MariaDyachenko** [comment]
Народився 14 червня 1946 року в районі Джамейка (Куїнс, Нью-Йорк).
1968 г. - після закінчення Вортона Трамп отримує ступінь бакалавра наук з економіки та спеціалізацію в сфері фінансів.
1971 році Трамп переїхав на Манхеттен
1995 г. - об'єднання казино в відкриту акціонерну компанію Trump Hotels & Casino Resorts.
З кінця 1990-х Трамп працює над декількома проектами, пов'язаними з будівництвом хмарочосів - готелів і офісних будівель.
16 червня 2015 року Трамп оголосив про те, що вступає в боротьбу за пост президента США.
8 листопада 2016 здобув перемогу на виборах президента США, обійшовши кандидата від Демократичної партії Хілларі Клінтон.
20 січня 2017 року відбулася церемонія інавгурації 45-го президента США Дональда Трампа.
