### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by MariiaZolotarova** [MariiaZolotarova/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by MariaDyachenko** [comment]
**Громадянство:** США
**Національність:** американець
**Освіта**: Пенсильванський університет
**Мови:** Англійська, Українська
**Сім'я**: Одружений втретє, маю п'ятеро дітей і семеро онуків. 

**Сильні сторони:** 

- Стійкий електорат і Трампізм
- Виконані економічні обіцянки
- Обвинувачення в сексизмі та расизмі працюють на мою користь
- Геополітичні зрушення
- Слабкі супротивники

**Слабкі сторони:**

- Вічна боротьба з Конгресом
- Сильні проізраїльські позиції
- Охорона здоров'я
- Екологія
- Несподівані скандали

**Хоббі:** Захоплююся грою в гольф. Є членом клубу Winged Foot Golf Club в Мамаронеке, штат Нью-Йорк, а також регулярно беру участь в змаганнях на своїх майданчиках. Я фанат Федора Емельяненко і не пропустив жодного його бою на території США .Є вболівальником американської футбольної команди Нью-Інгленд Петріотс 

**Нагороди:**
_Американські_

- Почесна медаль острова Елліс (15 жовтня 1986). Вручено на церемонії на острові Елліс, в тому числі разом з Розою Паркс і Мохаммедом Алі .

_Іноземні_

- Президентський орден «Сяйво» (Грузія, 21 квітня 2012) . Вручений президентом Грузії Михайлом Саакашвілі на церемонії в президентському палаці під час візиту Трампа в Тбілісі .

- Орден короля Абдель-Азіза з ланцюгом (Саудівська Аравія, 20 травня 2017) . Вручений хранителем двох святинь королем Саудівської Аравії Салманом ібн Абдул-Азізом Аль Саудом під час візиту Трампа в Ер-Ріяд.

- Золота медаль «За хоробрість» від вождів племен провінції Логар (Афганістан, 13 січня 2018) .
